# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-31 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id_found', models.CharField(db_index=True, max_length=64)),
                ('open_id_lost', models.CharField(db_index=True, max_length=64)),
                ('id_num', models.CharField(db_index=True, max_length=64)),
                ('contact_way', models.CharField(max_length=256)),
                ('kind', models.IntegerField()),
                ('status', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id_found', models.CharField(db_index=True, max_length=64)),
                ('open_id_lost', models.CharField(db_index=True, max_length=64)),
                ('pic_url', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('contact_way', models.CharField(max_length=256)),
                ('kind', models.IntegerField()),
                ('status', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('kind', models.IntegerField()),
                ('status', models.IntegerField()),
                ('object1', models.CharField(max_length=256)),
                ('object2', models.CharField(max_length=256)),
                ('object3', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('student_id', models.CharField(db_index=True, max_length=32)),
                ('rank', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('left_claim_num', models.IntegerField(default=5)),
                ('last_claim_time', models.DateField(null=True)),
            ],
        ),
    ]
