# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20160502_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64)),
                ('id_num', models.CharField(db_index=True, max_length=64, unique=True)),
                ('contact_way', models.CharField(max_length=256)),
                ('kind', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64)),
                ('pic_url', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('contact_way', models.CharField(max_length=256)),
                ('kind', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('kind', models.IntegerField()),
                ('status', models.IntegerField()),
                ('object1', models.CharField(max_length=256)),
                ('object2', models.CharField(max_length=256)),
                ('object3', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='activity',
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
