# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20161205_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='end_time',
            field=models.DateField(null=True),
        ),
    ]
