# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_auto_20161205_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='others',
            old_name='open_id',
            new_name='open_id_found',
        ),
        migrations.AddField(
            model_name='others',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='open_id_lost',
            field=models.CharField(db_index=True, default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='others',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
