# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_auto_20161211_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_claim_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='left_claim_num',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
